name: Firebase Deployment

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment when a PR is made to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Set up Firebase credentials and API key as environment variables
    - name: Set Firebase credentials
      run: |
        echo "$FIREBASE_CREDENTIALS_JSON" > firebase-credentials.json
        echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> $GITHUB_ENV
      env:
        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

    # Run your Python script (e.g., the one using Firebase)
    - name: Run Python script
      run: |
        python login.py